/* Hexdump main function, assembly language version */

	.section .text

	.globl main
	
main:
	/* TODO: add your code here */
	
; hex_read:
; 	/* TODO: implement */
; 	ret

	
; hex_write_string:
; 	/* TODO: implement */
; 	ret

	
; hex_format_offset:
; 	/* TODO: implement */
; 	ret

	
; hex_format_byte_as_hex:
; 	/* TODO: implement */
; 	ret

/*
hex_to_printable:
	movq , %rdi
	
 	ret
	
	ret

 */

/* vim:ft=gas:
 */
